vnpay:
  tmnCode: ${VNP_TMN_CODE}
  hashSecret: ${VNP_HASH_SECRET}
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: https://cartoon-nail-underfed.ngrok-free.dev/api/payment/return
  ipnUrl: https://cartoon-nail-underfed.ngrok-free.dev/api/payment/ipn



  #// SECRET KEY dung dang ky token (256bit 32 ky tu)
  #// server dùng key này de:
  #// -tao chu ky (sign)
  #// -verify token khi client gui lên

jwt:
  secret: ${JWT_SECRET}

